extern crate ctest;
extern crate shell_words;

static X11_TYPES: &[&str] = &[
    "Window",
    "GtkPlug",
    "GtkPlugClass",
    "GtkSocket",
    "GtkSocketClass",
];

fn pkg_config_cflags() -> Result<Vec<String>, Box<std::error::Error>> {
    let mut cmd = std::process::Command::new("pkg-config");
    cmd.arg("--cflags");
    cmd.arg("gtk+-3.0");
    let out = cmd.output()?;
    if !out.status.success() {
        return Err(format!("command {:?} returned {}",
                           &cmd, out.status).into());
    }
    let stdout = std::str::from_utf8(&out.stdout)?;
    Ok(shell_words::split(stdout.trim())?)
}

fn main() {
    let target = std::env::var("TARGET").unwrap();
    let windows = target.contains("windows");

    let mut cfg = ctest::TestGenerator::new();

    for flag in pkg_config_cflags().unwrap() {
        cfg.flag(&flag);
    }

    cfg.header("gtk/gtk.h");
    cfg.header("gtk/gtk-a11y.h");
    if !windows {
        cfg.header("gtk/gtkx.h");
    }

    cfg.skip_const(|_| true);
    cfg.skip_fn(|_| true);
    cfg.skip_signededness(|_| true);

    cfg.type_name(|ty, _is_struct, _is_union| {
        // Use Foo, instead of struct Foo, etc.
        ty.to_string()
    });

    cfg.skip_field(|typ, field| match (typ, field) {
        // Bit fields:
        ("GtkAccelKey", "accel_flags") => true,
        ("GtkBindingSet", "parsed") => true,
        ("GtkContainerClass", "_handle_border_width") => true,
        ("GtkMenuItemClass", "hide_on_activate") => true,
        ("GtkMenuShellClass", "submenu_placement") => true,
        ("GtkRcStyle", "engine_specified") => true,

        _ => false,
    });

    cfg.skip_field_type(|typ, field| match (typ, field) {
        // FIXME: void* / void**:
        ("GtkBuildableIface", "custom_tag_end") => true,
        // FIXME: int / int*
        ("GtkMenuItemClass", "toggle_size_request") => true,

        // FIXME: const mismatch:
        ("GtkCellAreaClass", "set_cell_property") => true,
        ("GtkColorChooserInterface", "get_rgba") => true,
        ("GtkRecentFilterInfo", "applications") => true,
        ("GtkRecentFilterInfo", "groups") => true,
        ("GtkRecentFilterInfo", "set_child_property") => true,
        ("GtkContainerClass", "set_child_property") => true,

        // FIXME: functions pointer vs void**:
        (_, "__gtk_reserved1") => true,
        (_, "__gtk_reserved2") => true,
        (_, "__gtk_reserved3") => true,
        (_, "__gtk_reserved4") => true,

        // Unnamed types:
        ("GtkBindingArg", "d") => true,

        _ => false,
    });

    cfg.field_name(|_typ, field| match field {
        // Restore original field names:
        "box_" => "box",
        "move_" => "move",
        "priv_" => "priv",
        "type_" => "type",
        _ => field,
    }.to_string());

    cfg.skip_type(move |typ| match typ {
        t if windows => X11_TYPES.contains(&t),
        _ => false,
    });

    cfg.skip_struct(move |typ| match typ {
        // Incomplete types:
        "GtkAboutDialogPrivate" => true,
        "GtkAccelGroupPrivate" => true,
        "GtkAccelLabelPrivate" => true,
        "GtkAccelMap" => true,
        "GtkAccelMapClass" => true,
        "GtkAccessiblePrivate" => true,
        "GtkActionBarPrivate" => true,
        "GtkActionGroupPrivate" => true,
        "GtkActionPrivate" => true,
        "GtkActionable" => true,
        "GtkActivatable" => true,
        "GtkAdjustmentPrivate" => true,
        "GtkAlignmentPrivate" => true,
        "GtkAppChooser" => true,
        "GtkAppChooserButtonPrivate" => true,
        "GtkAppChooserDialogPrivate" => true,
        "GtkAppChooserWidgetPrivate" => true,
        "GtkApplicationPrivate" => true,
        "GtkApplicationWindowPrivate" => true,
        "GtkArrowAccessiblePrivate" => true,
        "GtkArrowPrivate" => true,
        "GtkAspectFramePrivate" => true,
        "GtkAssistantPrivate" => true,
        "GtkBinPrivate" => true,
        "GtkBindingEntry" => true,
        "GtkBooleanCellAccessiblePrivate" => true,
        "GtkBoxPrivate" => true,
        "GtkBuildable" => true,
        "GtkBuilderPrivate" => true,
        "GtkButtonAccessiblePrivate" => true,
        "GtkButtonBoxPrivate" => true,
        "GtkButtonPrivate" => true,
        "GtkCalendarPrivate" => true,
        "GtkCellAccessibleParent" => true,
        "GtkCellAccessiblePrivate" => true,
        "GtkCellAreaBoxPrivate" => true,
        "GtkCellAreaContextPrivate" => true,
        "GtkCellAreaPrivate" => true,
        "GtkCellEditable" => true,
        "GtkCellLayout" => true,
        "GtkCellRendererAccelPrivate" => true,
        "GtkCellRendererClassPrivate" => true,
        "GtkCellRendererComboPrivate" => true,
        "GtkCellRendererPixbufPrivate" => true,
        "GtkCellRendererPrivate" => true,
        "GtkCellRendererProgressPrivate" => true,
        "GtkCellRendererSpinPrivate" => true,
        "GtkCellRendererSpinnerPrivate" => true,
        "GtkCellRendererTextPrivate" => true,
        "GtkCellRendererTogglePrivate" => true,
        "GtkCellViewPrivate" => true,
        "GtkCheckMenuItemAccessiblePrivate" => true,
        "GtkCheckMenuItemPrivate" => true,
        "GtkClipboard" => true,
        "GtkColorButtonPrivate" => true,
        "GtkColorChooser" => true,
        "GtkColorChooserDialogPrivate" => true,
        "GtkColorChooserWidgetPrivate" => true,
        "GtkColorSelectionDialogPrivate" => true,
        "GtkColorSelectionPrivate" => true,
        "GtkComboBoxAccessiblePrivate" => true,
        "GtkComboBoxPrivate" => true,
        "GtkComboBoxTextPrivate" => true,
        "GtkContainerAccessiblePrivate" => true,
        "GtkContainerCellAccessiblePrivate" => true,
        "GtkContainerPrivate" => true,
        "GtkCssProviderPrivate" => true,
        "GtkCssSection" => true,
        "GtkDialogPrivate" => true,
        "GtkEditable" => true,
        "GtkEntryAccessiblePrivate" => true,
        "GtkEntryBufferPrivate" => true,
        "GtkEntryCompletionPrivate" => true,
        "GtkEntryIconAccessible" => true,
        "GtkEntryPrivate" => true,
        "GtkEventBoxPrivate" => true,
        "GtkEventController" => true,
        "GtkEventControllerClass" => true,
        "GtkExpanderAccessiblePrivate" => true,
        "GtkExpanderPrivate" => true,
        "GtkFileChooser" => true,
        "GtkFileChooserButtonPrivate" => true,
        "GtkFileChooserDialogPrivate" => true,
        "GtkFileChooserNative" => true,
        "GtkFileChooserWidgetPrivate" => true,
        "GtkFileFilter" => true,
        "GtkFixedPrivate" => true,
        "GtkFlowBoxAccessiblePrivate" => true,
        "GtkFontButtonPrivate" => true,
        "GtkFontChooser" => true,
        "GtkFontChooserDialogPrivate" => true,
        "GtkFontChooserWidgetPrivate" => true,
        "GtkFontSelectionDialogPrivate" => true,
        "GtkFontSelectionPrivate" => true,
        "GtkFrameAccessiblePrivate" => true,
        "GtkFramePrivate" => true,
        "GtkGesture" => true,
        "GtkGestureClass" => true,
        "GtkGestureDrag" => true,
        "GtkGestureDragClass" => true,
        "GtkGestureLongPress" => true,
        "GtkGestureLongPressClass" => true,
        "GtkGestureMultiPress" => true,
        "GtkGestureMultiPressClass" => true,
        "GtkGesturePan" => true,
        "GtkGesturePanClass" => true,
        "GtkGestureRotate" => true,
        "GtkGestureRotateClass" => true,
        "GtkGestureSingle" => true,
        "GtkGestureSingleClass" => true,
        "GtkGestureSwipe" => true,
        "GtkGestureSwipeClass" => true,
        "GtkGestureZoom" => true,
        "GtkGestureZoomClass" => true,
        "GtkGradient" => true,
        "GtkGridPrivate" => true,
        "GtkHSVPrivate" => true,
        "GtkHandleBoxPrivate" => true,
        "GtkHeaderBarPrivate" => true,
        "GtkIMContextSimplePrivate" => true,
        "GtkIMMulticontextPrivate" => true,
        "GtkIconFactoryPrivate" => true,
        "GtkIconInfo" => true,
        "GtkIconInfoClass" => true,
        "GtkIconSet" => true,
        "GtkIconSource" => true,
        "GtkIconThemePrivate" => true,
        "GtkIconViewAccessiblePrivate" => true,
        "GtkIconViewPrivate" => true,
        "GtkImageAccessiblePrivate" => true,
        "GtkImageCellAccessiblePrivate" => true,
        "GtkImageMenuItemPrivate" => true,
        "GtkImagePrivate" => true,
        "GtkInfoBarPrivate" => true,
        "GtkInvisiblePrivate" => true,
        "GtkLabelAccessiblePrivate" => true,
        "GtkLabelPrivate" => true,
        "GtkLabelSelectionInfo" => true,
        "GtkLayoutPrivate" => true,
        "GtkLevelBarAccessiblePrivate" => true,
        "GtkLevelBarPrivate" => true,
        "GtkLinkButtonAccessiblePrivate" => true,
        "GtkLinkButtonPrivate" => true,
        "GtkListBoxAccessiblePrivate" => true,
        "GtkListStorePrivate" => true,
        "GtkLockButtonAccessiblePrivate" => true,
        "GtkLockButtonPrivate" => true,
        "GtkMenuAccessiblePrivate" => true,
        "GtkMenuBarPrivate" => true,
        "GtkMenuButtonAccessiblePrivate" => true,
        "GtkMenuButtonPrivate" => true,
        "GtkMenuItemAccessiblePrivate" => true,
        "GtkMenuItemPrivate" => true,
        "GtkMenuPrivate" => true,
        "GtkMenuShellAccessiblePrivate" => true,
        "GtkMenuShellPrivate" => true,
        "GtkMenuToolButtonPrivate" => true,
        "GtkMessageDialogPrivate" => true,
        "GtkMiscPrivate" => true,
        "GtkModelButton" => true,
        "GtkMountOperationPrivate" => true,
        "GtkNotebookAccessiblePrivate" => true,
        "GtkNotebookPageAccessiblePrivate" => true,
        "GtkNotebookPrivate" => true,
        "GtkNumerableIconPrivate" => true,
        "GtkOrientable" => true,
        "GtkOverlayPrivate" => true,
        "GtkPadController" => true,
        "GtkPadControllerClass" => true,
        "GtkPageSetup" => true,
        "GtkPanedAccessiblePrivate" => true,
        "GtkPanedPrivate" => true,
        "GtkPaperSize" => true,
        "GtkPlacesSidebar" => true,
        "GtkPlacesSidebarClass" => true,
        "GtkPlugPrivate" => true,
        "GtkPopoverMenu" => true,
        "GtkPopoverPrivate" => true,
        "GtkPrintContext" => true,
        "GtkPrintOperationPreview" => true,
        "GtkPrintOperationPrivate" => true,
        "GtkPrintSettings" => true,
        "GtkProgressBarAccessiblePrivate" => true,
        "GtkProgressBarPrivate" => true,
        "GtkRadioActionPrivate" => true,
        "GtkRadioButtonAccessiblePrivate" => true,
        "GtkRadioButtonPrivate" => true,
        "GtkRadioMenuItemAccessiblePrivate" => true,
        "GtkRadioMenuItemPrivate" => true,
        "GtkRangeAccessiblePrivate" => true,
        "GtkRangePrivate" => true,
        "GtkRcContext" => true,
        "GtkRecentActionPrivate" => true,
        "GtkRecentChooser" => true,
        "GtkRecentChooserDialogPrivate" => true,
        "GtkRecentChooserMenuPrivate" => true,
        "GtkRecentChooserWidgetPrivate" => true,
        "GtkRecentFilter" => true,
        "GtkRecentInfo" => true,
        "GtkRecentManagerPrivate" => true,
        "GtkRendererCellAccessiblePrivate" => true,
        "GtkScaleAccessiblePrivate" => true,
        "GtkScaleButtonAccessiblePrivate" => true,
        "GtkScaleButtonPrivate" => true,
        "GtkScalePrivate" => true,
        "GtkScrollable" => true,
        "GtkScrolledWindowAccessiblePrivate" => true,
        "GtkScrolledWindowPrivate" => true,
        "GtkSelectionData" => true,
        "GtkSeparatorPrivate" => true,
        "GtkSeparatorToolItemPrivate" => true,
        "GtkSettingsPrivate" => true,
        "GtkShortcutLabel" => true,
        "GtkShortcutLabelClass" => true,
        "GtkShortcutsGroup" => true,
        "GtkShortcutsGroupClass" => true,
        "GtkShortcutsSection" => true,
        "GtkShortcutsSectionClass" => true,
        "GtkShortcutsShortcut" => true,
        "GtkShortcutsShortcutClass" => true,
        "GtkSizeGroupPrivate" => true,
        "GtkSocketPrivate" => true,
        "GtkSpinButtonAccessiblePrivate" => true,
        "GtkSpinButtonPrivate" => true,
        "GtkSpinnerAccessiblePrivate" => true,
        "GtkSpinnerPrivate" => true,
        "GtkStackSidebarPrivate" => true,
        "GtkStatusIconPrivate" => true,
        "GtkStatusbarAccessiblePrivate" => true,
        "GtkStatusbarPrivate" => true,
        "GtkStyle" => true,
        "GtkStyleContextPrivate" => true,
        "GtkStylePropertiesPrivate" => true,
        "GtkStyleProvider" => true,
        "GtkSwitchAccessiblePrivate" => true,
        "GtkSwitchPrivate" => true,
        "GtkSymbolicColor" => true,
        "GtkTableChild" => true,
        "GtkTablePrivate" => true,
        "GtkTableRowCol" => true,
        "GtkTargetList" => true,
        "GtkTearoffMenuItemPrivate" => true,
        "GtkTextAppearance" => true,
        "GtkTextAttributes" => true,
        "GtkTextBTree" => true,
        "GtkTextBufferPrivate" => true,
        "GtkTextCellAccessiblePrivate" => true,
        "GtkTextTagPrivate" => true,
        "GtkTextTagTablePrivate" => true,
        "GtkTextViewAccessiblePrivate" => true,
        "GtkTextViewPrivate" => true,
        "GtkThemeEngine" => true,
        "GtkThemingEnginePrivate" => true,
        "GtkToggleActionPrivate" => true,
        "GtkToggleButtonAccessiblePrivate" => true,
        "GtkToggleButtonPrivate" => true,
        "GtkToggleToolButtonPrivate" => true,
        "GtkToolButtonPrivate" => true,
        "GtkToolItemGroupPrivate" => true,
        "GtkToolItemPrivate" => true,
        "GtkToolPalettePrivate" => true,
        "GtkToolShell" => true,
        "GtkToolbarPrivate" => true,
        "GtkTooltip" => true,
        "GtkToplevelAccessiblePrivate" => true,
        "GtkTreeDragDest" => true,
        "GtkTreeDragSource" => true,
        "GtkTreeModel" => true,
        "GtkTreeModelFilterPrivate" => true,
        "GtkTreeModelSortPrivate" => true,
        "GtkTreePath" => true,
        "GtkTreeRowReference" => true,
        "GtkTreeSelectionPrivate" => true,
        "GtkTreeSortable" => true,
        "GtkTreeStorePrivate" => true,
        "GtkTreeViewAccessiblePrivate" => true,
        "GtkTreeViewColumnPrivate" => true,
        "GtkTreeViewPrivate" => true,
        "GtkUIManagerPrivate" => true,
        "GtkViewportPrivate" => true,
        "GtkWidgetAccessiblePrivate" => true,
        "GtkWidgetClassPrivate" => true,
        "GtkWidgetPath" => true,
        "GtkWidgetPrivate" => true,
        "GtkWindowAccessiblePrivate" => true,
        "GtkWindowGeometryInfo" => true,
        "GtkWindowGroupPrivate" => true,
        "GtkWindowPrivate" => true,

        // Unnamed type
        "GtkBindingArg_d" => true,
        "GtkTextAppearance_u1" => true,
        "GtkTextAttributes_u1" => true,

        t if windows => X11_TYPES.contains(&t),

        _ => false,
    });

    cfg.generate("../gtk-sys/src/lib.rs", "all.rs");
}

